pipeline: annotate-genes-trinotate
version: 1.0
parser:
  help: Annotate genes using Trinotate
  arg-groups:
    basic:
      args:
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        annotations-gff:
          help: "Annotations GFF"
          type: str
          required: True
          action: confirmFile
        trinotate-data-dir:
          help: "Trinotate database directory"
          type: str
          action: confirmDir
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: ""
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        downloads-dir:
          help: "Directory to store downloads"
          type: str
          default: "Downloads"
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        annotations-dir:
          help: "Directory to store annotations"
          type: str
          default: 
            str: "Annotations"
setup:
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly-version}.fa"
          out_dir: "{assembly-dir}"
          gzipped: False
  gff_input:
    file-method:
      input:
        args:
          - "annotations-gff"
          - "annotations-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{annotations-gff}"
          standardized_filename: "{species}_{assembly-version}.{annotation-version}.gff3"
          out_dir: "{annotations-dir}"
          gzipped: False
  trinotate_db:
    dir-method:
      input:
        args:
          - "trinotate-data-dir"
          - "downloads-dir"
      standardize:
        method: "dir-str"
        args:
          path_name: "{trinotate-data-dir}"
          standardized_directory: "Trinotate"
          out_dir: "{downloads-dir}"
          gzipped: False

snakefiles:
  - download_trinotate
  - annotations_trinotate