pipeline: annotate-genes-eggnog
version: 1.0
parser:
  help: Annotate genes using eggNOG
  arg-groups:
    basic:
      args:
        aa-transcript-fasta:
          help: "Amino acid transcript file"
          type: str
          required: True
          action: confirmFile
        eggnod-data-dir:
          help: "eggNOG database directory"
          type: str
          action: confirmDir
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: ""
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        downloads-dir:
          help: "Directory to store downloads"
          type: str
          default: "Downloads"
        annotations-dir:
          help: "Directory to store annotations"
          type: str
          default: 
            str: "Annotations"
setup:
  aa_transcript_input:
    file-method:
      input:
        args:
          - "aa-transcript-fasta"
          - "annotations-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{aa-transcript-fasta}"
          standardized_filename: "{species}_{assembly-version}.{annotation-version}_pep.fa"
          out_dir: "{annotations-dir}"
          gzipped: False
  eggnog_db:
    dir-method:
      input:
        args:
          - "eggnod-data-dir"
          - "downloads-dir"
      standardize:
        method: "dir-str"
        args:
          path_name: "{eggnod-data-dir}"
          standardized_directory: "EggNOG"
          out_dir: "{downloads-dir}"
          gzipped: False

snakefiles:
  - download_eggnog_database
  - annotations_eggnog_mapper