pipeline: annotate-utrs-peaks2utr
version: 1.0
parser:
  help: Annotate an 3prime-UTRs using peaks2utr using a merged BAM file
  arg-groups:
    basic:
      args:
        rnaseq-bam:
          help: "RNAseq BAM file"
          type: str
          required: True
          action: confirmFile
        rnaseq-copy-method:
          help: "Specifies if RNAseq BAM should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        annotations-gff:
          help: "Annotations GFF"
          type: str
          required: True
          action: confirmFile
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: ""
            suffix:
              - function: jobRandomString
        utr-version:
          help: "UTR Version"
          type: str
          default:
            str: ""
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString

setup:
  rnaseq_input:
    methods:
      file-str: "{rnaseq-bam}"
    args:
      standardized_filename: "RNAseq/BAM/{species}_{assembly-version}.bam"
      copy_method: "{rnaseq-copy-method}"
      gzipped: True

  gff_input:
    methods: 
      file-str: "{annotations-gff}"
    args:
      standardized_filename: "Annotations/{species}_{assembly-version}.{annotation-version}.gff3"
      copy_method: "copy"
      gzipped: False

snakemake:
  modules:
    - annotate_3primeUTRs_peaks2utr