pipeline: annotate-braker3-isoseq
version: 1.0
parser:
  help: Annotate an assembly using BRAKER3 using IsoSeq data
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        isoseq-standardized-wildcard:
          help: "Standardized wildcard statement used to store PacBio-HiFi BAMs"
          type: str
          default: 
            str: "{samples}.{exts}"
      args:
        isoseq-wildcard:
          help: "Wildcard statement to represent IsoSeq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "isoseq-standardized-wildcard"
        isoseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "isoseq-standardized-wildcard"
        isoseq-copy-method:
          help: "Specifies if IsoSeq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        isoseq-file-extensions:
          help: "Supports file extensions for PacBio-HiFi BAMs"
          type: list
          default:
            - "bam"
            - "bam.pbi"
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        hints-fasta:
          help: "Protein hints file"
          type: str
          required: True
          action: confirmFile
        fasta-copy-method:
          help: "Specifies if assembly and hints files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        busco-database:
          help: "Name of BUSCO database"
          type: str
          required: True
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        homology-dir:
          help: "Directory to store hint"
          type: str
          default: "Homology"
        index-dir:
          help: "Directory to store indices"
          type: str
          default: "Indices"
        downloads-dir:
          help: "Directory to store downloads"
          type: str
          default: "Downloads"
        pacbio-bam-dir:
          help: "Directory to store PacBio BAM files"
          type: str
          default: "IsoSeq/PacBio/"
        isoseq-fastq-dir:
          help: "Directory to store the FASTQs files"
          type: str
          default: "IsoSeq/FASTQs"
        isoseq-merged-bam-dir:
          help: "Directory to store BAM files"
          type: str
          default: "IsoSeq/BAMs/Merged"
        isoseq-aligned-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "IsoSeq/BAMs/Aligned"
        isoseq-sorted-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: 
            str: "IsoSeq/BAMs/Sorted"
        annotations-dir:
          help: "Directory to store annotations"
          type: str
          default: 
            str: "Annotations"
        repeatmodeler-dir:
          help: "Directory to store RepeatModeler output"
          type: str
          default: "Assembly/RepeatModeler"
setup:
  isoseq_input:
    wildcard-method:
      input:
        args:
          - "isoseq-wildcard"
          - "isoseq-standardized-wildcard"
          - "pacbio-bam-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{isoseq-wildcard}"
          standardized_filename: "{isoseq-standardized-wildcard}"
          out_dir: "{pacbio-bam-dir}"
          copy_method: '{isoseq-copy-method}'
          gzipped: True
          file_extensions: '{isoseq-file-extensions}'

      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{isoseq-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "isoseq-table"
          - "isoseq-standardized-wildcard"
          - "pacbio-bam-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{isoseq-table}"
          standardized_filename: "{isoseq-standardized-wildcard}"
          out_dir: "{pacbio-bam-dir}"
          copy_method: '{isoseq-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{isoseq-table}"
          sample_column: 'samples'
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly_version}.fa"
          out_dir: "{assembly-dir}"
          copy_method: "{fasta-copy-method}"
          gzipped: False

  hints_input:
    file-method:
      input:
        args:
          - "hints-fasta"
          - "homology-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{hints-fasta}"
          standardized_filename: "ProteinHints.fa"
          out_dir: "{homology-dir}"
          copy_method: "{fasta-copy-method}"
          gzipped: False

snakefiles:
  - iso_seq_fastqs
  - iso_seq_align_minimap2
  - iso_seq_sort
  - iso_seq_merge