pipeline: annotate-genes-eggnog
version: 1.0
parser:
  help: Annotate genes using eggNOG
  arg-groups:
    basic:
      args:
        aa-transcript-fasta:
          help: "Amino acid transcript file"
          type: str
          required: True
          action: confirmFile
        eggnog-data-dir:
          help: "eggNOG database directory"
          type: str
          action: confirmDir
        eggnog-copy-method:
          help: "Specifies if EggNOG directory should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: ""
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
setup:
  aa_transcript_input:
    methods: 
      file-str: "{aa-transcript-fasta}"
    args:
      standardized_filename: "Annotations/{species}_{assembly-version}.{annotation-version}_pep.fa"
      copy_method: "copy"
      gzipped: False
  
  eggnog_db:
    methods:
      dir-str: "{eggnog-data-dir}"
    args:
      standardized_directory: "Downloads/EggNOG"
      copy_method: "{eggnog-copy-method}"
      gzipped: False

snakemake:
  modules:
    - download_eggnog_database
    - annotations_eggnog_mapper