pipeline: assembly-check-contamination
version: 1.0
parser:
  help: Check for contamination in assembly using HiC data
  arg-groups:
    basic:
      args:
        hifi-fastq:
          help: "HIFI FASTQ file"
          type: str
          required: True
          action: confirmFile
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        busco-table:
          help: "BUSCO table file"
          type: str
          required: True
          action: confirmFile
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        blastx-max-length:
          help: "Maximum length of the blastx output"
          type: int
          default: 10000000
        ncbi-nt-db:
          help: "Path to the NCBI nt database"
          type: str
          required: True
        uniprot-db:
          help: "Path to the Uniprot database"
          type: str
          required: True
          action: confirmFile
        ncbi-taxa-db:
          help: "Path to the NCBI taxa database"
          type: str
          required: True
          action: confirmDir
setup:
  hifi_input:
    methods:
      file-str: "{hifi-fastq}"
    args:
      standardized_filename: "{species}.fq.gz"
      copy_method: symbolic_link
      gzipped: True

  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "{species}_{assembly_version}.fa"
      copy_method: copy
      gzipped: False

  busco_input:
    methods:
      file-str:  "{busco-table}"
    args:
      standardized_filename: "{species}_{assembly_version}.busco.full_table.tsv"
      copy_method: copy
      gzipped: False

snakemake:
  modules:
    - assembly_contamination_blobtools
