pipeline: atacseq-peaks-macs3
version: 1.0
parser:
  help: Generate peaks for bulk ATAC-Seq data using bwa and MACS3
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        atacseq-standardized-wildcard: "{samples}_{reads}.fastq.gz"
      args:
        atacseq-wildcard:
          help: "Wildcard statement to represent ATACseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "atacseq-standardized-wildcard"
        atacseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "atacseq-standardized-wildcard"
        atacseq-copy-method:
          help: "Specifies if ATACseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        genome-size:
          help: "Genome size in basepairs for focal species"
          type: int
          required: True
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
setup:
  fastq_file_input:
    methods:
      wildcard-str: "{atacseq-wildcard}"
      table-file: "{atacseq-table}"
    args:  
      standardized_filename: "ATAC_seq/FASTQ/{atacseq-standardized-wildcard}"
      copy_method: '{atacseq_copy_method}'
      gzipped: True
      sample_keywords: 
        - 'samples'
    snakefiles:
      - fastq_process_wildcards

  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/{species}_{assembly_version}.fa"
      gzipped: False
  
snakemake:
  modules:
    - atac_seq_align_bwa
    - atac_seq_sort_samtools
    - atac_seq_dedup_sambamba
    - atac_seq_peaks_MACS3
  links:
    - input: fastq_process_single_end
      output: bwa_mem_single_end_atac_seq
    - input: fastq_process_paired_end
      output: bwa_mem_pair_end_atac_seq
