pipeline: correct-splice-variants-flair
version: 1.0
parser:
  help: Correct splice variants using flair
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        reseq-standardized-filename: "{samples}_{reads}.fq.gz"
      args:
        reseq-wildcard:
          help: "Wildcard statement to represent reseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-filename"
        reseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-filename"
        reseq-copy-method:
          help: "Specifies if reseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-gtf:
          help: "Assembly GTF"
          type: str
          required: True
          action: confirmFile
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
setup:
  reseq_input:
    methods:
      wildcard-str: "{reseq-wildcard}"
      table-file: "{reseq-table}"
    args:
      standardized_filename: "IsoSeq/FASTQ/{reseq-standardized-filename}"
      copy_method: '{reseq-copy-method}'
      gzipped: True
      sample_keywords:
        - "samples"
  
  assembly_fasta:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/{species}_{assembly-version}.fa"
      copy_method: copy
      gzipped: False
  
  assembly_gtf:
    methods:
      file-str: "{assembly-gtf}"
    args:
      standardized_filename: "Annotations/{species}_{assembly-version}.{annotation-version}.gtf"
      copy_method: copy
      gzipped: False

snakemake:
  modules:
    - iso_seq_splice_variants_flair