pipeline: correct-splice-variants-flair
version: 1.0
parser:
  help: Correct splice variants using flair
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        reseq-standardized-wildcard:
          help: "Standardized wildcard statement used to store reseq FASTQs"
          type: str
          default: 
            str: "{samples}_{reads}.fq.gz"
      args:
        reseq-wildcard:
          help: "Wildcard statement to represent reseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-wildcard"
        reseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-wildcard"
        reseq-copy-method:
          help: "Specifies if reseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-gtf:
          help: "Assembly GTF"
          type: str
          required: True
          action: confirmFile
        splice-junctions:
          help: "Splice junctions file"
          type: str
          action: confirmFile
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        annotation-version:
          help: "Annotation Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        annotations-dir:
          help: "Directory to store annotation"
          type: str
          default: "Annotations"
        reseq-fastq-dir:
          help: "Directory to store the FASTQs files"
          type: str
          default: "reseq/FASTQs"
setup:
  reseq_input:
    wildcard-method:
      input:
        args:
          - "reseq-wildcard"
          - "reseq-standardized-wildcard"
          - "reseq-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{reseq-wildcard}"
          standardized_filename: "{reseq-standardized-wildcard}"
          out_dir: "{reseq-fastq-dir}"
          copy_method: '{reseq-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{reseq-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "reseq-table"
          - "reseq-standardized-wildcard"
          - "reseq-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{reseq-table}"
          standardized_filename: "{reseq-standardized-wildcard}"
          out_dir: "{reseq-fastq-dir}"
          copy_method: '{reseq-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{fastq-table}"
          sample_column: 'samples'
  
  assembly_fasta:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
          - "assembly-version"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly-version}.fa"
          out_dir: "{assembly-dir}"
          copy_method: copy
          gzipped: False
  
  assembly_gtf:
    file-method:
      input:
        args:
          - "assembly-gtf"
          - "annotations-dir"
          - "assembly-version"
          - "annotation-version"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-gtf}"
          standardized_filename: "{species}_{assembly-version}.{annotation-version}.gtf"
          out_dir: "{annotations-dir}"
          copy_method: copy
          gzipped: False
  splice_junctions:
    file-method:
      input:
        args:
          - "splice-junctions"
          - "assembly-dir"
          - "assembly-version"
      standardize:
        method: "file-str"
        args:
          input_filename: "{splice-junctions}"
          standardized_filename: "{species}_{assembly-version}.SJ.tab"
          out_dir: "{assembly-dir}"
          copy_method: copy
          gzipped: False

snakefiles:
  - iso_seq_splice_variants_flair