pipeline: hic-scaffolds-yahs
version: 1.0
parser:
  help: Scaffold an assembly with Hi-C data using YAHs
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        hic-standardized-wildcard:
          help: "Standardized wildcard statement used to store HiC FASTQs"
          type: str
          default: 
            str: "{samples}_{reads}.fq.gz"
      args:
        hic-wildcard:
          help: "Wildcard statement to represent HiC FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "hic-standardized-wildcard"
        hic-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "hic-standardized-wildcard"
        hic-copy-method:
          help: "Specifies if HiC FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        assembly-sample:
          help: "Assembly sample name"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        hic-fastq-dir:
          help: "Directory to store the HiC files"
          type: str
          default: "HiC/FASTQs"
        hic-aligned-bam-dir:
          help: "Directory to store the aligned HiC BAM files"
          type: str
          default: "HiC/BAMs/Aligned"
        hic-sorted-bam-dir:
          help: "Directory to store the sorted HiC BAM files"
          type: str
          default: "HiC/BAMs/Sorted"
        hic-yahs-dir:
          help: "Directory to store the yahs output"
          type: str
          default: "HiC/yahs"
setup:
  reseq_input:
    wildcard-method:
      input:
        args:
          - "hic-wildcard"
          - "hic-standardized-wildcard"
          - "hic-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{hic-wildcard}"
          standardized_filename: "{hic-standardized-wildcard}"
          out_dir: "{hic-fastq-dir}"
          copy_method: '{hic-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{hic-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "hic-table"
          - "hic-standardized-wildcard"
          - "hic-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{hic-table}"
          standardized_filename: "{hic-standardized-wildcard}"
          out_dir: "{hic-fastq-dir}"
          copy_method: '{hic-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{hic-table}"
          sample_column: 'samples'
  
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{assembly_sample}.fa"
          out_dir: "{assembly-dir}"
          copy_method: "{fasta-copy-method}"
          gzipped: False
snakefiles:
  - hic_scaffolds_yahs