pipeline: hic-scaffolds-yahs
version: 1.0
parser:
  help: Scaffold an assembly with Hi-C data using YAHs
  arg-groups:
    basic:
      mutually-exclusive-args:
        hic-parser:
          required: True
      wildcards-args:
        hic-standardized-suffix: "{reads}.fq.gz"
      args:
        hic-wildcard:
          help: "Wildcard statement to represent the a single pair of HiC FASTQs"
          type: str
          mutually-exclusive: "hic-parser"
          wildcards: "hic-standardized-suffix"
        hic-table:
          help: "Table with the filenames of a single pair of HiC FASTQs"
          type: str
          action: confirmFile
          mutually-exclusive: "hic-parser"
          wildcards: "hic-standardized-suffix"
        hic-copy-method:
          help: "Specifies if HiC FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Wildcard statement to represent assembly FASTAs"
          type: str
          action: confirmFile
          required: True
        assembly-copy-method:
          help: "Specifies if the assembly FASTA should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
setup:
  hic_input:
    methods:
      wildcard-str: "{hic-wildcard}"
      table-file: "{hic-table}"
    args:
      standardized_filename: "HiC/FASTQ/{species}_HiC_{hic-standardized-suffix}"
      copy_method: '{hic-copy-method}'
      gzipped: True
  
  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/hifiasm/{species}_{assembly_version}.fa"
      copy_method: "{assembly-copy-method}"
      gzipped: False

snakemake:
  modules:
  - hic_scaffolds_yahs
