pipeline: lr-reseq-align-minimap2
version: 1.0
parser:
  help: Align long reads to a genome assembly using minimap2
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        reseq-standardized-wildcard:
          help: "Standardized wildcard statement used to store reseq FASTQs"
          type: str
          default: 
            str: "{samples}_{reads}.fq.gz"
      args:
        reseq-wildcard:
          help: "Wildcard statement to represent reseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-wildcard"
        reseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "reseq-standardized-wildcard"
        reseq-copy-method:
          help: "Specifies if reseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        index-dir:
          help: "Directory to store indices"
          type: str
          default: "Indices"
        reseq-fastq-dir:
          help: "Directory to store the FASTQs files"
          type: str
          default: "reseq/FASTQs"
        reseq-aligned-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "reseq/BAMs/Aligned"
        reseq-sorted-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "reseq/BAMs/Sorted"
        reseq-coverage-dir:
          help: "Directory to store coverage files"
          type: str
          default: "reseq/Coverage"
setup:
  reseq_input:
    wildcard-method:
      input:
        args:
          - "reseq-wildcard"
          - "reseq-standardized-wildcard"
          - "reseq-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{reseq-wildcard}"
          standardized_filename: "{reseq-standardized-wildcard}"
          out_dir: "{reseq-fastq-dir}"
          copy_method: '{reseq-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{reseq-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "reseq-table"
          - "reseq-standardized-wildcard"
          - "reseq-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{reseq-table}"
          standardized_filename: "{reseq-standardized-wildcard}"
          out_dir: "{reseq-fastq-dir}"
          copy_method: '{reseq-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{fastq-table}"
          sample_column: 'samples'
  
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly_version}.fa"
          out_dir: "{assembly-dir}"
          copy_method: "{assembly-copy-method}"
          gzipped: False
snakefiles:
  - lr_reseq_align_minimap2
  - index_assembly
  - reseq_sort
  - reseq_bam_coverage
  - reseq_plot_coverage
  


