pipeline: mask-assembly
version: 1.0
parser:
  help: Mask an assembly using RepeatModeler
  arg-groups:
    basic:
      args:
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
setup:
  assembly_input:
    methods: 
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/{species}_{assembly_version}.fa"
      copy_method: "{assembly-copy-method}"
      gzipped: False

snakemake:
  modules:
    - repeatmasking
