pipeline: mask-assembly
version: 1.0
parser:
  help: Mask an assembly using RepeatModeler
  arg-groups:
    basic:
      args:
        assembly-fasta:
          help: "Assembly file"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        repeatmodeler-dir:
          help: "Directory to store RepeatModeler output"
          type: str
          default: "Assembly/RepeatModeler"
setup:
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly_version}.fa"
          out_dir: "{assembly-dir}"
          copy_method: "{assembly-copy-method}"
          gzipped: False

snakefiles:
  - repeatmasking
