pipeline: msf-amino-acid-species-tree
version: 1.0
parser:
  help: Create a species tree from amino acid MSF files using wASTRAL.
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        msf-standardized-filename: "{samples}.fa"
      args:
        msf-wildcard:
          help: "Wildcard statement to represent MSF files"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "msf-standardized-filename"
        msf-table:
          help: "Table with sample and MSF filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "msf-standardized-filename"
        msf-copy-method:
          help: "Specifies if MSFs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        id-mappings:
          help: "File with mappings of gene tree tip names to species names."
          type: str
          action: confirmFile
          required: True
    clipkit_params:
      args:
        trim-method:
          help: "Method to use for trimming alignments with ClipKIT"
          choices:
            - 'smart-gap'
            - 'entropy'
            - 'gappy'
            - 'block-gappy'
            - 'gappyout'
            - 'composition-bias'
            - 'heterotachy'
            - 'kpic'
            - 'kpic-smart-gap'
            - 'kpic-gappy'
            - 'kpi'
            - 'kpi-smart-gap'
            - 'kpi-gappy'
            - 'c3'
            - 'cst'
          default: 'smart-gap'
setup:
  msf_input:
    methods:
      wildcard-str: "{msf-wildcard}"
      table-file: "{msf-table}"
    args:
      standardized_filename: "MSF/AA/{msf-standardized-filename}"
      copy_method: '{msf-copy-method}'
      sample_keywords:
        - "samples"
  id_mappings:
    methods:
      file-str: "{id-mappings}"
    args:
      standardized_filename: "wASTRAL/id_mappings.txt"
      copy_method: 'copy'

snakemake:
  modules:
    - msf_align_muscle
    - msf_align_muscle_aa_links
    - msa_trim_clipkit
    - msa_tree_iqtree
    - msf_phylogeny_aa_links
    - tre_infer_species_tree_wASTRAL
