pipeline: pacbio-filter
version: 1.0
parser:
  help: Filter PacBio BAM files using fastp
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        pacbio-standardized-wildcard:
          help: "Standardized wildcard statement used to store PacBio BAM files"
          type: str
          default: 
            str: "{samples}.bam"
      args:
        pacbio-wildcard:
          help: "Wildcard statement to represent PacBio BAM files"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "pacbio-standardized-wildcard"
        pacbio-table:
          help: "Table with sample and PacBio BAM filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "pacbio-standardized-wildcard"
        pacbio-copy-method:
          help: "Specifies if PacBio BAMs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        min-length:
          help: "Minimum length of reads to keep"
          type: int
          default:
            str: "200"
        cut-front:
          help: "Trim from the front of the reads"
          action: store_true
        cut-tail:
          help: "Trim from the tail of the reads"
          action: store_true
        cut-right:
          help: "Trim the right side of the reads, starting from the 5' end"
          action: store_true
    paths:
      args:
        pacbio-bam-dir:
          help: "Directory to store PacBio BAM files"
          type: str
          default: 
            str: "PacBio/"
        unfiltered-fastq-dir:
          help: "Directory to store unfiltered FASTQ files"
          type: str
          default: 
            str: "FASTQ/Unfiltered"
        filtered-fastq-dir:
          help: "Directory to store filtered FASTQ files"
          type: str
          default: 
            str: "FASTQ/Filtered"
setup:
  pacbio_input:
    wildcard-method:
      input:
        args:
          - "pacbio-wildcard"
          - "pacbio-standardized-wildcard"
          - "pacbio-bam-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{pacbio-wildcard}"
          standardized_filename: "{pacbio-standardized-wildcard}"
          out_dir: "{pacbio-bam-dir}"
          copy_method: '{pacbio-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{pacbio-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "pacbio-table"
          - "pacbio-standardized-wildcard"
          - "pacbio-bam-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{pacbio-table}"
          standardized_filename: "{pacbio-standardized-wildcard}"
          out_dir: "{pacbio-bam-dir}"
          copy_method: '{pacbio-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{pacbio-table}"
          sample_column: 'samples'

snakefiles:
  - pacbio_to_fastq
  - fastq_filter_fastp
