pipeline: reseq-calc-xpnsl
parser:
  help: Calculate XP-nSL using selscan
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        reseq-copy-method:
          help: "Socifies if resequencing files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        model-file:
          help: "Model filename"
          type: str
          required: True
          action: confirmFile
        model-name:
          help: "Model name"
          type: str
          required: True
        pop-name:
          help: "Reference population name"
          type: str
          required: True
        maf:
          help: "Minor allele frequency"
          type: float
          default: 0.05
        bins:
          help: "Number of bins for normalization"
          type: int
          default: 100
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        work-dir:
          help: "Assign the working directory for snakemake"
          type: str
          default:
            str: "Calc_nSL"
            suffix:
              - function: jobTimeStamp
              - function: jobRandomString
        snakemake-job-prefix:
          help: "Assign the snakemake job prefix"
          type: str
          default:
            str: "Calc_nSL"
            suffix:
              - function: jobTimeStamp
              - function: jobRandomString
    paths:
      args:
        reseq-filtered-vcf-dir:
          help: "Directory to store filtered VCFs files"
          type: str
          default: "reSEQ/VCFs/Unphased"
        reseq-phased-vcf-dir:
          help: "Directory to store phased VCFs files"
          type: str
          default: "reSEQ/VCFs/Phased"
        reseq-popgen-dir:
          help: "Directory to store resequencing population genetics analyses"
          type: str
          default: "reSEQ/PopGen"
        models-dir:
          help: "Directory to store models"
          type: str
          default: "Models"
setup:
  reseq_vcf:
    file-method:
      input:
        args:
          - "work-dir"
          - "reseq-vcf"
          - "species"
          - "assembly-version"
          - "reseq-filtered-vcf-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{reseq-vcf}"
          standardized_filename: "{species}_{assembly-version}.vcf.gz"
          out_dir: "{reseq-filtered-vcf-dir}"
          work_dir: '{work-dir}'
          copy_method: '{reseq-copy-method}'
          gzipped: True

  model_input:
    file-method:
      input:
        args:
          - "work-dir"
          - "model-file"
          - "models-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{model-file}"
          standardized_filename: "{species}.model"
          out_dir: "{models-dir}"
          work_dir: '{work-dir}'
          gzipped: False
  
command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - reseq_phase_shapeit4.smk
  - reseq_pop_ind_file.smk
  - reseq_calc_xpnsl_selscan.smk