pipeline: reseq-gwas
parser:
  help: GWAS on resequencing data using GEMMA
  args:
    params:
      reseq-wildcard:
        help: "Wildcard statement to represent resequencing PLINK files"
        type: str
        required: True
      reseq-copy-method:
        help: "Socifies if resequencing files should be copied or symbolically linked."
        choices:
          - 'symbolic_link'
          - 'copy'
        default: 'symbolic_link'
      model-file:
        help: "Model filename"
        type: str
        required: True
        action: confirmFile
      model-categories:
        help: "Model categories"
        type: str
        nargs: '+'
        required: True
      kinship-matrix:
        help: "Kinship matrix type"
        type: int
        default: 1
      linear-model:
        help: "Linear model type"
        type: int
        default: 1
      maf:
        help: "MAF cutoff"
        type: float
        default: 0.05
      min-log-pvalue:
        help: "Minimum log10 p-values to keep"
        type: float
        default: 0.5
      assembly-version:
        help: "Assembly Version"
        type: str
        default:
          str: "v"
          suffix:
            - function: jobRandomString
      species:
        help: "Species name"
        type: str
        default:
          str: "Sp"
          suffix:
            - function: jobRandomString
      work-dir:
        help: "Assign the working directory for snakemake"
        type: str
        default:
          str: "reSEQ_GWAS"
          suffix:
            - function: jobTimeStamp
            - function: jobRandomString
      snakemake-job-prefix:
        help: "Assign the snakemake job prefix"
        type: str
        default:
          str: "reSEQ_GWAS"
          suffix:
            - function: jobTimeStamp
            - function: jobRandomString
    paths:
      models-dir:
        help: "Directory to store models"
        type: str
        default: "Models"
      reseq-bed-dir:
        help: "Directory to store resequencing PLINK BED files"
        type: str
        default: "reSEQ/BEDs"
      reseq-gwas-dir:
        help: "Directory to store the resequencing GWAS results"
        type: str
        default: "reSEQ/GWAS"
setup:
  reseq_input:
    wildcard-method:
      input:
        args:
          - "work-dir"
          - "reseq-wildcard"
          - "reseq-bed-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{reseq-wildcard}"
          standardized_filename: "{species}_{assembly_version}.{{ext}}"
          out_dir: "{reseq-bed-dir}"
          work_dir: '{work-dir}'
          copy_method: '{reseq-copy-method}'
  
  model_input:
    file-method:
      input:
        args:
          - "work-dir"
          - "model-file"
          - "models-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{model-file}"
          standardized_filename: "{species}.model"
          out_dir: "{models-dir}"
          work_dir: '{work-dir}'
          copy_method: '{reseq-copy-method}'
          gzipped: False

command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - reseq_gwas_gemma.smk

