pipeline: filter-model-vcf
version: 1.0
parser:
  help: Filter a model in resequencing VCF files using bcftools
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        reseq-copy-method:
          help: "Specifies if resequencing files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        model-file:
          help: "Model filename"
          type: str
          required: True
          action: confirmFile
        model-name:
          help: "Model name"
          type: str
          required: True
        missing-cutoff:
          help: "Missing data cutoff"
          type: float
          default: 0.25
        maf-cutoff:
          help: "MAF cutoff"
          type: float
          default: 0.05
        qual-cutoff:
          help: "Quality cutoff"
          type: float
          default: 30
        min-alleles:
          help: "Minimum allele count"
          type: int
          default: 2
        max-alleles:
          help: "Maximum allele count"
          type: int
          default: 2
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString

setup:
  reseq_vcf:
    methods:
      file-str: "{reseq-vcf}"
    args:
      standardized_filename: "reSEQ/VCF/Unfiltered/{species}_{assembly-version}.vcf.gz"
      copy_method: '{reseq-copy-method}'
      gzipped: True
  
  model_input:
    methods:
      file-str: "{model-file}"
    args:
      standardized_filename: "Models/{species}.model"
      copy_method: 'copy'
      gzipped: False

snakemake:
  modules:
    - reseq_filter_w_model_bcftools.smk
    - reseq_model_ind_file.smk