pipeline: reseq-calc-nsl
version: 1.0
parser:
  help: Calculate nSL using selscan
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        reseq-copy-method:
          help: "Specifies if resequencing files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        maf:
          help: "Minor allele frequency"
          type: float
          default: 0.05
        window-size:
          help: "Window size for nSL calculation"
          type: int
          default: 10000
        bins:
          help: "Number of bins for normalization"
          type: int
          default: 100
        exclude-chr:
          help: "List of chromosomes to exclude from analysis"
          type: str
          nargs: '+'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString

setup:
  reseq_vcf:
    methods:
      file-str: "{reseq-vcf}"
    args:
      standardized_filename: "reSEQ/VCF/Unfiltered/{species}_{assembly-version}.vcf.gz"
      copy_method: '{reseq-copy-method}'
      gzipped: True

snakemake:
  modules:
    - reseq_filter_selscan
    - reseq_calc_nsl_selscan