pipeline: filter-model-vcf
parser:
  help: Filter a model in resequencing VCF files using bcftools
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        model-file:
          help: "Model filename"
          type: str
          required: True
          action: confirmFile
        model-name:
          help: "Model name"
          type: str
          required: True
        missing-cutoff:
          help: "Missing data cutoff"
          type: float
          default: 0.25
        maf-cutoff:
          help: "MAF cutoff"
          type: float
          default: 0.05
        qual-cutoff:
          help: "Quality cutoff"
          type: float
          default: 30
        min-alleles:
          help: "Minimum allele count"
          type: int
          default: 2
        max-alleles:
          help: "Maximum allele count"
          type: int
          default: 2
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
    paths:
      args:
        reseq-unfiltered-vcf-dir:
          help: "Directory to store VCFs files"
          type: str
          default: "reSEQ/VCFs/Unfiltered"
        reseq-filtered-vcf-dir:
          help: "Directory to store VCFs files"
          type: str
          default: "reSEQ/VCFs/Filtered"
        models-dir:
          help: "Directory to store models"
          type: str
          default: "Models"

setup:
  reseq_vcf:
    file-method:
      input:
        args:
          - "work-dir"
          - "reseq-vcf"
          - "species"
          - "assembly-version"
          - "reseq-unfiltered-vcf-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{reseq-vcf}"
          standardized_filename: "{species}_{assembly-version}.vcf.gz"
          out_dir: "{reseq-unfiltered-vcf-dir}"
          work_dir: '{work-dir}'
          gzipped: True

  model_input:
    file-method:
      input:
        args:
          - "work-dir"
          - "model-file"
          - "models-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{model-file}"
          standardized_filename: "{species}.model"
          out_dir: "{models-dir}"
          work_dir: '{work-dir}'
          gzipped: False
  
command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - reseq_filter_w_model_bcftools.smk
  - reseq_model_ind_file.smk