pipeline: filter-vcf
version: 1.0
parser:
  help: Filter resequencing VCF files using bcftools
  arg-groups:
    basic:
      mutually-exclusive-args:
        region-args:
          required: False
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        reseq-copy-method:
          help: "Specifies if resequencing files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        missing-cutoff:
          help: "Missing data cutoff"
          type: float
          default: 0.25
        maf-cutoff:
          help: "MAF cutoff"
          type: float
          default: 0.05
        qual-cutoff:
          help: "Quality cutoff"
          type: float
          default: 30
        min-alleles:
          help: "Minimum allele count"
          type: int
          default: 2
        max-alleles:
          help: "Maximum allele count"
          type: int
          default: 2
        include-regions:
          help: "Region(s) to include. Multiple regions can be specified by separating them with a comma."
          type: str
          mutually-exclusive: "region-args"
        exclude-regions:
          help: "Region(s) to exclude. Multiple regions can be specified by separating them with a comma."
          type: str
          mutually-exclusive: "region-args"
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString

setup:
  reseq_vcf:
    methods:
      file-str: "{reseq-vcf}"
    args:
      standardized_filename: "reSEQ/VCF/Unfiltered/{species}_{assembly-version}.vcf.gz"
      copy_method: '{reseq-copy-method}'
      gzipped: True

snakemake:
  modules:
    - reseq_filter_bcftools.smk