pipeline: reseq-calc-nsl
version: 1.0
parser:
  help: Calculate nSL using selscan
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        reseq-copy-method:
          help: "Socifies if resequencing files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        maf:
          help: "Minor allele frequency"
          type: float
          default: 0.05
        bins:
          help: "Number of bins for normalization"
          type: int
          default: 100
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        reseq-filtered-vcf-dir:
          help: "Directory to store filtered VCFs files"
          type: str
          default: "reSEQ/VCFs/Unphased"
        reseq-phased-vcf-dir:
          help: "Directory to store phased VCFs files"
          type: str
          default: "reSEQ/VCFs/Phased"
        reseq-popgen-dir:
          help: "Directory to store resequencing population genetics analyses"
          type: str
          default: "reSEQ/PopGen"
setup:
  reseq_vcf:
    file-method:
      input:
        args:
          - "reseq-vcf"
          - "species"
          - "assembly-version"
          - "reseq-filtered-vcf-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{reseq-vcf}"
          standardized_filename: "{species}_{assembly-version}.vcf.gz"
          out_dir: "{reseq-filtered-vcf-dir}"
          copy_method: '{reseq-copy-method}'
          gzipped: True
  
command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - reseq_phase_shapeit4
  - reseq_calc_nsl_selscan