pipeline: rnaseq-align-star
version: 1.0
parser:
  help: Align RNAseq reads within a genome assembly using STAR
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        rnaseq-standardized-wildcard: "{samples}_{reads}.fq.gz"
      args:
        rnaseq-wildcard:
          help: "Wildcard statement to represent RNAseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-wildcard"
        rnaseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-wildcard"
        rnaseq-copy-method:
          help: "Specifies if RNAseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
setup:
  fastq_file_input:
    methods:
      wildcard-str: "{rnaseq-wildcard}"
      table-file: "{rnaseq-table}"
    args:
      standardized_filename: "RNAseq/FASTQ/{rnaseq-standardized-wildcard}"
      copy_method: '{rnaseq-copy-method}'
      gzipped: True
      sample_keywords: 
        - 'samples'
    snakefiles:
      - fastq_process_wildcards
  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/{species}_{assembly_version}.fa"
      copy_method: "{assembly-copy-method}"
      gzipped: False
  
snakemake:
  modules:
    - rna_seq_star_wo_gtf
    - rna_seq_sort
  links:
    - input: fastq_process_single_end
      output: star_single_end_rnaseq
    - input: fastq_process_paired_end
      output: star_pair_end_rnaseq
  

