pipeline: rnaseq-remove-multimaps
version: 1.0
parser:
  help: Count RNAseq reads within a genome assembly using STAR and featureCounts
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        rnaseq-standardized-wildcard:
          help: "Standardized wildcard statement used to store RNAseq FASTQs"
          type: str
          default: 
            str: "{samples}_{reads}.fq.gz"
      args:
        rnaseq-wildcard:
          help: "Wildcard statement to represent RNAseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-wildcard"
        rnaseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-wildcard"
        rnaseq-copy-method:
          help: "Specifies if RNAseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        index-dir:
          help: "Directory to store indices"
          type: str
          default: "Indices"
        rnaseq-fastq-dir:
          help: "Directory to store the unfiltered FASTQs files"
          type: str
          default: "RNAseq/FASTQs/Unfiltered"
        rnaseq-filtered-fastq-dir:
          help: "Directory to store the filtered FASTQs files"
          type: str
          default: "RNAseq/FASTQs/Filtered"
        rnaseq-aligned-bam-dir:
          help: "Directory to store aligned BAM files"
          type: str
          default: "RNAseq/BAMs/Aligned"
        rnaseq-sorted-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "RNAseq/BAMs/Sorted"
        
setup:
  rnaseq_input:
    wildcard-method:
      input:
        args:
          - "rnaseq-wildcard"
          - "rnaseq-standardized-wildcard"
          - "rnaseq-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{rnaseq-wildcard}"
          standardized_filename: "{rnaseq-standardized-wildcard}"
          out_dir: "{rnaseq-fastq-dir}"
          copy_method: '{rnaseq-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{rnaseq-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "rnaseq-table"
          - "rnaseq-standardized-wildcard"
          - "rnaseq-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{rnaseq-table}"
          standardized_filename: "{rnaseq-standardized-wildcard}"
          out_dir: "{rnaseq-fastq-dir}"
          copy_method: '{rnaseq-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{rnaseq-table}"
          sample_column: 'samples'
  
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly_version}.fa"
          out_dir: "{assembly-dir}"
          copy_method: "{assembly-copy-method}"
          gzipped: False

snakefiles:
  - rna_seq_star_remove_multimap
  - rna_seq_sort
  - rna_seq_bam_to_fastq


