pipeline: unmapped-fastqs-star
version: 1.0
parser:
  help: Create unmapped FASTQs using STAR
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        rnaseq-standardized-filename: "{samples}_{reads}.fq.gz"
      args:
        rnaseq-wildcard:
          help: "Wildcard statement to represent RNAseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-filename"
        rnaseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "rnaseq-standardized-filename"
        rnaseq-copy-method:
          help: "Specifies if RNAseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-gtf:
          help: "Assembly GTF"
          type: str
          required: True
          action: confirmFile
        assembly-copy-method:
          help: "Specifies if assembly files should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        read-len:
          help: "Read Length"
          type: str
          required: True
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
setup:
  rnaseq_input:
    methods:
      wildcard-str: "{rnaseq-wildcard}"
      table-filename: "{rnaseq-table}"
    args:
      standardized_filename: "RNAseq/FASTQ/{rnaseq-standardized-filename}"
      copy_method: '{rnaseq-copy-method}'
      gzipped: True
      sample_keywords: 
        - 'samples' 
  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/{species}_{assembly_version}.fa"
      copy_method: "{assembly-copy-method}"
      gzipped: False
  gtf_input:
    methods:
      file-str: "{assembly-gtf}"
    args:
      standardized_filename: "Assembly/{species}_{assembly_version}.gtf"
      copy_method: "{assembly-copy-method}"
      gzipped: False

snakemake:
  modules:
    - star_create_index
    - rna_seq_star_multimap_fastqs


