pipeline: rnaseq-counts-star
parser:
  help: Count RNAseq reads within a genome assembly using STAR and featureCounts
  arg-groups:
    basic:
      mutually-exclusive-groups:
        input-parser:
          required: True
      args:
        rnaseq-wildcard:
          help: "Wildcard statement to represent RNAseq FASTQs"
          type: str
          mutually-exclusive: "input-parser"
        rnaseq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
        rnaseq-copy-method:
          help: "Socifies if RNAseq FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        rnaseq-standardized-wildcard:
          help: "Standardized wildcard statement used to store RNAseq FASTQs"
          type: str
          default: 
            str: "{sample}_{read}.fq.gz"
        assembly-fasta:
          help: "Assembly fasta"
          type: str
          required: True
          action: confirmFile
        assembly-gtf:
          help: "Assembly GTF"
          type: str
          required: True
          action: confirmFile
        read-len:
          help: "Read Length"
          type: int
          required: True
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
    paths:
      args:
        assembly-dir:
          help: "Directory to store assembly"
          type: str
          default: "Assembly"
        index-dir:
          help: "Directory to store indices"
          type: str
          default: "Indices"
        rnaseq-fastq-dir:
          help: "Directory to store the FASTQs files"
          type: str
          default: "RNAseq/FASTQs"
        rnaseq-splice-aligned-dir:
          help: "Directory to store BAM files"
          type: str
          default: "RNAseq/SpliceJunctions/Aligned"
        rnaseq-bam-dir:
          help: "Directory to store BAM files"
          type: str
          default: "RNAseq/BAMs"
        rnaseq-aligned-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "RNAseq/BAMs/Aligned"
        rnaseq-sorted-bam-dir:
          help: "Directory to store sorted BAM files"
          type: str
          default: "RNAseq/BAMs/Sorted"
        rnaseq-count-dir:
          help: "Directory to store RNAseq counts"
          type: str
          default: "RNAseq/Counts" 
setup:
  rnaseq_input:
    wildcard-method:
      input:
        args:
          - "rnaseq-wildcard"
          - "rnaseq-standardized-wildcard"
          - "rnaseq-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{rnaseq-wildcard}"
          standardized_filename: "{rnaseq-standardized-wildcard}"
          out_dir: "{rnaseq-fastq-dir}"
          copy_method: '{rnaseq_copy_method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{rnaseq-wildcard}"
          sample_wildcard: 'sample'

    table-method:
      input:
        args:
          - "rnaseq-table"
          - "rnaseq-standardized-wildcard"
          - "rnaseq-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{rnaseq-table}"
          standardized_filename: "{rnaseq-standardized-wildcard}"
          out_dir: "{rnaseq-fastq-dir}"
          copy_method: '{rnaseq_copy_method}'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{rnaseq-table}"
  
  assembly_input:
    file-method:
      input:
        args:
          - "assembly-fasta"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-fasta}"
          standardized_filename: "{species}_{assembly_version}.fa"
          out_dir: "{assembly-dir}"
          gzipped: False
  
  gtf_input:
    file-method:
      input:
        args:
          - "assembly-gtf"
          - "assembly-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{assembly-gtf}"
          standardized_filename: "{species}_{assembly_version}.gtf"
          out_dir: "{assembly-dir}"
          gzipped: False

command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - rna_seq_2pass_star
  - rna_seq_sort
  - rna_seq_feature_counts


