pipeline: seperate-pop-vcfs
version: 1.0
parser:
  help: Create separate VCF files for each population in a resequencing VCF file
  arg-groups:
    basic:
      args:
        reseq-vcf:
          help: "Resequencing VCF file"
          type: str
          required: True
          action: confirmFile
        model-file:
          help: "Model filename"
          type: str
          required: True
          action: confirmFile
        model-name:
          help: "Model name"
          type: str
          required: True
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString
    paths:
      args:
        reseq-unfiltered-vcf-dir:
          help: "Directory to store VCFs files"
          type: str
          default: "reSEQ/VCFs/Unfiltered"
        reseq-filtered-vcf-dir:
          help: "Directory to store VCFs files"
          type: str
          default: "reSEQ/VCFs/Filtered"
        models-dir:
          help: "Directory to store models"
          type: str
          default: "Models"

setup:
  reseq_vcf:
    file-method:
      input:
        args:
          - "reseq-vcf"
          - "species"
          - "assembly-version"
          - "reseq-unfiltered-vcf-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{reseq-vcf}"
          standardized_filename: "{species}_{assembly-version}.vcf.gz"
          out_dir: "{reseq-unfiltered-vcf-dir}"
          gzipped: True

  model_input:
    file-method:
      input:
        args:
          - "model-file"
          - "models-dir"
      standardize:
        method: "file-str"
        args:
          input_filename: "{model-file}"
          standardized_filename: "{species}.model"
          out_dir: "{models-dir}"
          gzipped: False
  
command-line:
  cores: 20
  use-singularity: True

snakefiles:
  - reseq_separate_pop_bcftools.smk