pipeline: tracking-naps
version: 1.0
parser:
  help: Track MP4 videos using SLEAP and NAPS
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        video-standardized-filename: "{video_ids}.mp4"
      args:
        video-wildcard:
          help: "Wildcard statement to represent videos to track"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "video-standardized-filename"
        video-table:
          help: "Table with video IDs and filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "video-standardized-filename"
        video-copy-method:
          help: "Specifies if videos should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        centroid-model:
          help: "Centroid model directory"
          type: str
          required: True
          action: confirmDir
        instance-model:
          help: "Instance model directory"
          type: str
          required: True
          action: confirmDir
        model-copy-method:
          help: "Specifies if models should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        tag-node-name:
          help: "Name of the ArUco tag node"
          type: str
          required: True
    sleap-params:
      args:
        tracking-batch-size:
          help: "Batch size for tracking"
          type: int
          default: 4
        tracking-tracker:
          help: "Tracker to use for tracking"
          type: str
        tracking-similarity:
          help: "Similarity threshold for tracking"
          type: str
          choices:
            - 'instance'
            - 'normalized_instance'
            - 'object_keypoint'
            - 'centroid'
            - 'iou'
        tracking-post-connect-single-breaks:
          help: "If non-zero and target_instance_count is also non-zero, then connect track breaks when exactly one track is lost and exactly one track is spawned in frame."
          type: int
        tracking-pre-cull-to-target:
          help: "If non-zero and target_instance_count is also non-zero, then cull instances over target count per frame before tracking"
          type: int
        tracking-target-instance-count:
          help: "Target number of instances to track per frame"
          type: int
        tracking-clean-instance-count:
          help: "Target number of instances to clean after tracking"
          type: int
        tracking-max-tracking:
          help: "If true then the tracker will cap the max number of tracks. Set the max number of tracks with --tracking-max-tracks"
          action: store_true
        tracking-max-tracks:
          help: "Maximum number of tracks to keep"
          type: int
    naps-params:
      args:
        start-frame:
          help: "Start frame for tracking"
          type: int
          required: True
        end-frame:
          help: "End frame for tracking"
          type: int
          required: True
        aruco-marker-set:
          help: "Aruco marker set"
          type: str
          required: True
          choices:
            - 'DICT_4X4_50'
            - 'DICT_4X4_100'
            - 'DICT_4X4_250'
            - 'DICT_4X4_1000'
            - 'DICT_5X5_50'
            - 'DICT_5X5_100'
            - 'DICT_5X5_250'
            - 'DICT_5X5_1000'
            - 'DICT_6X6_50'
            - 'DICT_6X6_100'
            - 'DICT_6X6_250'
            - 'DICT_6X6_1000'
            - 'DICT_7X7_50'
            - 'DICT_7X7_100'
            - 'DICT_7X7_250'
            - 'DICT_7X7_1000'
            - 'DICT_ARUCO_ORIGINAL'
        half-rolling-window-size:
          help: "Half of the rolling window size"
          type: int
          default: 20
        aruco-crop-size:
          help: "Size of the crop for Aruco markers"
          type: int
          default: 50
        aruco-error-correction-rate:
          help: "Error correction rate for Aruco markers"
          type: float
          default: 0.6
        aruco-adaptive-thresh-constant:
          help: "Adaptive threshold constant for Aruco markers"
          type: int
          default: 7
        aruco-adaptive-thresh-win-size-max:
          help: "Maximum adaptive threshold window size for Aruco markers"
          type: int
          default: 23
        aruco-adaptive-thresh-win-size-step:
          help: "Step size for adaptive threshold window size for Aruco markers"
          type: int
          default: 10
        aruco-adaptive-thresh-win-size-min:
          help: "Minimum adaptive threshold window size for Aruco markers"
          type: int
          default: 3
setup:
  video_input:
    methods:
      wildcard-str: "{video-wildcard}"
      table-file: "{video-table}"
    args:
      standardized_filename: "Tracking/Videos/{video-standardized-filename}"
      copy_method: '{video-copy-method}'
      sample_keywords: 
        - 'video_ids'
  centroid_model:
    methods:
      dir-str: "{centroid-model}"
    args:
      standardized_directory: "Tracking/Models/centroid_model"
      copy_method: "{model-copy-method}"
  instance_model:
    methods:
      dir-str: "{instance-model}"
    args:
      standardized_directory: "Tracking/Models/instance_model"
      copy_method: "{model-copy-method}"

snakemake:
  modules:
    - tracking_sleap
    - tracking_naps
