pipeline: trim-fastqs
version: 1.0
parser:
  help: Trim short reads FASTQ files using fastp
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      wildcards-args:
        fastq-standardized-wildcard:
          help: "Standardized wildcard statement used to store FASTQs"
          type: str
          default: 
            str: "{samples}_{reads}.fq.gz"
        sra-standardized-wildcard:
          help: "Standardized wildcard used to store SRAs"
          type: str
          default:
            str: "samples"
      args:
        fastq-wildcard:
          help: "Wildcard statement to represent FASTQs"
          type: str
          mutually-exclusive: "input-parser"
          wildcards: "fastq-standardized-wildcard"
        fastq-table:
          help: "Table with sample and FASTQs filenames"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "fastq-standardized-wildcard"
        paired-end-sra:
          help: "Table with SRA accession numbers for paired-end reads"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "sra-standardized-wildcard"
        single-end-sra:
          help: "Table with SRA accession numbers for single-end reads"
          type: str
          action: confirmFile
          mutually-exclusive: "input-parser"
          wildcards: "sra-standardized-wildcard"
        fastq-copy-method:
          help: "Specifies if FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        min-length:
          help: "Minimum length of reads to keep"
          type: int
          default:
            str: "50"
        cut-front:
          help: "Trim from the front of the reads"
          action: store_true
        cut-tail:
          help: "Trim from the tail of the reads"
          action: store_true
        cut-right:
          help: "Trim the right side of the reads, starting from the 5' end"
          action: store_true
    paths:
      args:
        untrimmed-fastq-dir:
          help: "Directory to store untrimmed FASTQ files"
          type: str
          default: 
            str: "FASTQ/Untrimmed"
        trimmed-fastq-dir:
          help: "Directory to store trimmed FASTQ files"
          type: str
          default: 
            str: "FASTQ/Trimmed"
        sra-download-dir:
          help: "Directory to store downloaded SRA files"
          type: str
          default: 
            str: "FASTQ/SRA"
        sra-processed-dir:
          help: "Directory to store processed SRA files"
          type: str
          default: 
            str: "FASTQ/Untrimmed"
setup:
  fastq_input:
    wildcard-method:
      input:
        args:
          - "fastq-wildcard"
          - "fastq-standardized-wildcard"
          - "untrimmed-fastq-dir"
      standardize:
        method: "wildcard-str"
        args:
          wildcard_str: "{fastq-wildcard}"
          standardized_filename: "{fastq-standardized-wildcard}"
          out_dir: "{untrimmed-fastq-dir}"
          copy_method: '{fastq-copy-method}'
          gzipped: True
      samples:
        method: "wildcard-str"
        args:
          wildcard_str: "{fastq-wildcard}"
          sample_wildcards: 
            - 'samples'

    table-method:
      input:
        args:
          - "fastq-table"
          - "fastq-standardized-wildcard"
          - "untrimmed-fastq-dir"
      standardize:
        method: "table-file"
        args:
          table_filename: "{fastq-table}"
          standardized_filename: "{fastq-standardized-wildcard}"
          out_dir: "{untrimmed-fastq-dir}"
          copy_method: '{fastq-copy-method}'
          sample_column: 'samples'
          gzipped: True
      samples:
        method: "table-file"
        args:
          table_filename: "{fastq-table}"
          sample_column: 'samples'
    paired-end-sra-method:
      input:
        args:
          - "paired-end-sra"
          - "sra-download-dir"
      samples:
        method: "table-file"
        args:
          table_filename: "{paired-end-sra}"
          sample_column: "{sra-standardized-wildcard}"
      snakefiles: 
        - "fastq_sra_paired_end_download"
    single-end-sra-method:
      input:
        args:
          - "single-end-sra"
          - "sra-download-dir"
      samples:
        method: "table-file"
        args:
          table_filename: "{single-end-sra}"
          sample_column: "{sra-standardized-wildcard}"
      snakefiles: 
        - "fastq_sra_single_end_download"

snakefiles:
  - fastq_trim_fastp
