repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.2
    hooks:
      - id: snakefmt
