# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}

package:
  name: pipemake
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 0
  entry_points:
    - pipemake=pipemake.pipemake:main

source:
  path: ../../

requirements:
  host:
    - pip
    - python >=3.11

  run:
    - pip
    - python >=3.11
    - bioconda::snakemake >=8.11.3
    - pytest

test:
  imports:
    - pipemake
  run:
    - pipemake --help
