name: pipemake-docs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bioconda::snakemake
  - conda-forge::pip>=23.2.1
  - pip:
    - sphinx-copybutton
    - sphinx-press-theme
    - sphinx-book-theme
    - sphinx-argparse
    - linkify-it-py
