name: Conda w/ Pipelines Upload

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: pipemake
          environment-file: .conda/environment_build.yml
          python-version: 3.9
          channels: conda-forge,bioconda,conda-forge/label/python_rc
      - name: Setup (${{ matrix.os }})
        run: |
          conda install -y conda-build main::anaconda-client
      - name: Build (${{ matrix.os }}) - External
        run: |
          conda build .conda/pipemake --output-folder build
      - name: Activate base
        run: |
          conda activate base
      - name: Upload Windows
        if: matrix.os == 'windows-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda -t "$env:ANACONDA_API_TOKEN" upload --force --user kocherlab build/win-64/*.conda
      - name: Upload MacOS
        if: matrix.os == 'macos-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda -t "$env:ANACONDA_API_TOKEN" upload --user kocherlab build/osx-arm64/*.condad
      - name: Upload Ubuntu
        if: matrix.os == 'ubuntu-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda -t "$ANACONDA_API_TOKEN" upload --force --user kocherlab build/linux-64/*.conda
        
